// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package profile

type Data struct {
	// 资源名称
	Name string `json:"name"`
	// 资源描述
	Description string `json:"description"`
	// 资源类型
	Style string `json:"style"`
	// 所属服务
	Service string `json:"service"`
	// 权限（w、r）
	Mode string `json:"mode"`
	// 创建时间
	CreateTime string `json:"createTime"`
	// 更新时间
	UpdateTime string `json:"updateTime"`
}

type Role struct {
	// 角色名称
	Name string `json:"name"`
	// 角色描述
	Description string `json:"description"`
	// 创建时间
	CreateTime string `json:"createTime"`
	// 更新时间
	UpdateTime string `json:"updateTime"`
}

type RoleInput struct {
	// 角色名称
	Name string `json:"name"`
	// 角色描述
	Description string `json:"description"`
}

type RoleOperateInput struct {
	// 角色名称
	RoleName string `json:"roleName"`
	// 资源名称
	DataName string `json:"dataName"`
}

type SetUserInput struct {
	// 用户名
	Name *string `json:"name"`
	// 密码
	Passwd *string `json:"passwd"`
	// 用户描述
	Description *string `json:"description"`
}

type User struct {
	// 用户名
	Name string `json:"name"`
	// 用户描述
	Description string `json:"description"`
	// 用户密码
	Password string `json:"password"`
	// 创建时间
	CreateTime string `json:"createTime"`
	// 更新时间
	UpdateTime string `json:"updateTime"`
}

type UserBelongInput struct {
	// 用户名称
	UserName string `json:"userName"`
	// 角色名称
	RoleName string `json:"roleName"`
}

type UserInput struct {
	// 用户名
	Name string `json:"name"`
	// 密码
	Passwd string `json:"passwd"`
	// 用户描述
	Description string `json:"description"`
}
