// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package inventory

type DeleteUserPassInput struct {
	// 主机ip/hostname
	Host string `json:"host"`
	// 远程操作用户
	RemoteUser string `json:"remote_user"`
}

type Group struct {
	// 主机分组名称
	Name string `json:"name"`
	// 主机分组描述
	Description string `json:"description"`
	// 创建时间
	CreateTime string `json:"createTime"`
	// 更新时间
	UpdateTime string `json:"updateTime"`
}

type GroupInput struct {
	// 分组名称
	Name string `json:"name"`
	// 分组描述
	Description string `json:"description"`
}

type Host struct {
	// 主机名
	Name string `json:"name"`
	// 主机描述
	Description string `json:"description"`
	// 远程主机的python解释器（默认为/usr/bin/python）
	RemotePythonInterpreter string `json:"remote_python_interpreter"`
	// 创建时间
	CreateTime string `json:"createTime"`
	// 更新时间
	UpdateTime string `json:"updateTime"`
}

type HostBelongInput struct {
	// 主机名称
	HostName string `json:"hostName"`
	// 角色名称
	GroupName string `json:"groupName"`
}

type HostInput struct {
	// 主机名称
	Name string `json:"name"`
	// 主机描述
	Description string `json:"description"`
	// python解释器
	RemotePythonInterpreter string `json:"remote_python_interpreter"`
}

type RemoteUserPass struct {
	// 远程操作用户
	RemoteUser string `json:"remote_user"`
	// 远程操作用户密码
	RemotePass string `json:"remote_pass"`
}

type SetHostInput struct {
	// 主机名称
	Name *string `json:"name"`
	// 主机描述
	Description *string `json:"description"`
	// python解释器
	RemotePythonInterpreter *string `json:"remote_python_interpreter"`
}

type UserPassInput struct {
	// 主机ip/hostname
	Host string `json:"host"`
	// 远程操作用户（host/ip@username）
	RemoteUser string `json:"remote_user"`
	// 远程操作用户密码
	RemotePass string `json:"remote_pass"`
}
